name: flutter_apns
description: APNS push notification plugin. Uses firebase_messaging on Android, but replaces it on iOS with custom implementation.
version: 1.6.0
homepage: https://github.com/mwaylabs/flutter-apns

plugin:
  platforms:
    android:
      pluginClass: FirebasePushConnector
    ios:
      pluginClass: ApnsPushConnector

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 3.6.0
  firebase_messaging: 15.1.3
  flutter_apns_only: ^1.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
